### ISSUE TITLE
Descriptor function defined() bug

### ISSUE THREAD

**Issue by mirazasx** [postmanlabs/generic-bitmask#9]
Hi,

descriptor function defined() returns wrong result in cases when you try to check first bit.

F.e. 
`descriptors = new Descriptor({
        read: 0,
        write: 1
    });`

> first bit count start at zero, not at one as in the example, bacause Math.pow(2, value) needs 0 in order to set first bit

then later on in the code, if you ask descriptors.defined("read") you will get false.
This: 
!!this.hash[name] is falsy when value is 0, it probably could be 
(this.hash[name] !== undefined) 
then at least in this case returns true.

Code from descriptor.js
`defined: function (name, lazy) {
        return Array.isArray(name) ? (name.length ? name.every(function (name) {
            return this.defined(name, lazy);
        }, this) : !!lazy) : (name ? !!this.hash[name] : !!lazy);
    },`

Please let me know if I'm wrong here og please fix it or I can do that, it's only one line of code in my opinion.

Cheers Mantas G.

**Comment by shamasis** [comment]
Zero base is not possible in bitmask. 😞

**Comment by roobie** [comment]
Yeah, as @shamasis points out, this is not an issue, because any value AND'ed with zero is always zero:

Try for yourself in e.g. the browser console
```javascript
1 & 0 // 0
2 & 0 // 0
4 & 0 // 0
// etc.
```

So the solution is to start at `1`:
```javascript
 descriptors = new Descriptor({ read: 1, write: 2 });
```

**Comment by mirazasx** [comment]
Is 0 not possible, how do I do bitmask/flag which is not set? Is has to be 0 bit, otherswise value is always 1, which doesn't make much sense to have it.
My case is that if I have a flag which identifies different parameters on object lets say: 
1- byte test 1 passed, 
2- byte test 2 passed, 
3- byte test 3 passed 
So field value would be 0 if non of tests is taken and 7 if all three tests is taken
Descriptor will return false result for the first bit, If I do as @roobie  says, it's always gonna be 1 or 15 which is weird.

But anyway thanks for the answer, I understand that Descriptor is probably meant to something else not to describe the meaning of bytes in the bitmask ;)

**Comment by roobie** [comment]
Yes, `0` means that no bits in the bitmask are set, i.e.

```javascript
var read = 1
var write = 2

var bitmask = 0
var isRead = Boolean(read & bitmask) // false
var isWrite = Boolean(write & bitmask) // false

// whereas:
var bitmask = 3
var isRead = Boolean(read & bitmask) // true
var isWrite = Boolean(write & bitmask) // true
```

**Comment by mirazasx** [comment]
@roobie  that I understand the concept of it, I have been using bit masks for last 10years all over the code, what I think that I misunderstood is that purpose of Desciptor class, it takes dec values to define what bitmask bits means, not bit index (what i was expecting). Using Descriptor with todays implementation makes it impossible to check first bit if it's set or not.
In other words I expected that:
`descriptors = new Descriptor({ read: 1, write: 2, execute:4 });` means
000 - first bit read, second bit for write, third bit for execute, but appierently that's not what it does.

**Comment by roobie** [comment]
Oh, I see. I apologize for being thick :laughing:

**Comment by shamasis** [comment]
@mirazasx - that is intentional. The goal is to abstract out the bit concept for people who do not understand it. Descriptors are for that - it helps "describing" the mask i.e. give names to the mask and an easy to understand index where internally the index refers to bit positions and not the bits.

Have a look at the readme example:

```
// create a new instance of bitmask
var mask = new Bitmask(),
    descriptors = new Descriptor({
        read: 1,
        write: 2
    });

// Set the mask flags for the mask
descriptor.add('read', mask);
descriptor.validate('read', mask); // returns true
descriptor.extract(mask); // returns ['read']
descriptor.remove('read', mask);

// Check if bit names are set
descriptor.defined('read') // returns true
```

On the other hand the `Mask` object works with raw bitmasks. I am closing this issue. Let me know if my approach is utterly screwed up or maybe I need to write down these thoughts on readme. :-)

Maybe I could simplify the descriptor API by accepting an array of strings `descriptors = new Descriptor(['read', 'write', 'execute']` and then use the array index as bit positions. The downside to that is once you set it like this, you do not have room to add things in between or change the order of the same for already defined descriptors.

**Comment by mirazasx** [comment]
@shamasis could you provide an example of how do I set first bit to 1 or 0 and check if it's set using Descriptor? That's when I faced problem with Descriptor :)  That would be appreciated, so I don't have to maintain my own version which handles it correctly. The example witch is given din't worked for me with first bit for some reason.

**Comment by roobie** [comment]
Maybe this helps:
```javascript
var Bitmask = require('generic-bitmask').Mask,
    Descriptor = require('generic-bitmask').Descriptor;

// create a new instance of bitmask
var mask = new Bitmask(),
// the descriptor here means:
//       unused|write|read
// bits: ... 00     0    0
// positions:       2    1
descriptor = new Descriptor({
      //name: position
        read: 1,
        write: 2
    });

// current state of mask: 0000
// Set the mask flags for the mask
descriptor.add('read', mask); // sets bit one to 1
// current state of mask: 0001
v = descriptor.validate('read', mask); // returns true, i.e. bit one === 1
console.log(v)
descriptor.remove('read', mask);
// current state of mask: 0000
v = descriptor.validate('read', mask); // returns false, i.e. bit one === 0
console.log(v)

descriptor.add('write', mask); // sets bit two to 1
// current state of mask: 0010
v = descriptor.validate('write', mask); // returns false, i.e. bit one === 1
console.log(v)

```
